[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4",
    "pyaudio>=0.2.14",
    "pyinstaller>=6.12.0",
    "scipy>=1.15.2",
]
