name: Build and Release Executable

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pyaudio numpy scipy
          
      - name: Build executable
        run: |
          pyinstaller --name=FootstepSoundEnhancer --onefile --noconsole --clean main.py
          
      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: FootstepSoundEnhancer-Windows
          path: dist/FootstepSoundEnhancer.exe
          
  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: FootstepSoundEnhancer-Windows
          path: windows-build
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Footstep Sound Enhancer ${{ steps.get_tag.outputs.TAG }}
          body: |
            # Footstep Sound Enhancer ${{ steps.get_tag.outputs.TAG }}
            
            A desktop application that enhances footstep sounds in games by analyzing and selectively amplifying audio in real-time.
            
            ## Installation
            
            1. Download the executable for your platform
            2. No installation required - just run the downloaded file
            
            ## Documentation
            
            For more information, see the [README](https://github.com/${{ github.repository }}/blob/main/README.md) and [User Guide](https://github.com/${{ github.repository }}/blob/main/USER_GUIDE.md).
          files: |
            windows-build/FootstepSoundEnhancer.exe
          tag_name: ${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false